### ISSUE TITLE
Disallow python operators in catalog entries

### ISSUE THREAD

**Issue by observingClouds** [eurec4a/eurec4a-intake#144]
A few catalog entries, [especially those of HALO](https://github.com/eurec4a/eurec4a-intake/blob/6df5e39d67071508da1a4d7e8d3cd03c4aced870/HALO/BAHAMAS_PositionAttitude.yaml#L6), have hyphens in their names.

This disallows auto-completion and the usage of the following syntax:
```python
ds = cat.HALO.Bahamas.PositionAttitude.HALO-0115.to_dask()
```
but rather needs to written as:
```python
ds = cat.HALO.Bahamas.PositionAttitude['HALO-0115'].to_dask()
```

I would argue that we replace operators `*`,`-`,`+`,`/` with e.g. `_` so that both versions are possible. In this particular case I wonder if the prefix `HALO-` is at all necessary and we should rather use that space to write out the entire date e.g. `20200115`.

**Comment by observingClouds** [comment]
@d70-t @RobertPincus any opinions?

**Comment by d70-t** [comment]
I totally agree, that those are annoing and `HALO-` is redundant at that scope.

I'd however pefer not to change them, because of two reasons:
* those identifiers are the EUREC4A flight identifiers. We've e.g. [been advertising](https://howto.eurec4a.eu/specmacs.html#finding-the-corresponding-specmacs-dataset) to use the `flight_id` from the segmentation effort to retrieve data from the catalog.
* we should try not to change names in the catalog unless really really necessary. Changing names will break user code and will be annoying and it's likely not immediately clear what went wrong. (`intake_warning` might help here)

**Comment by RobertPincus** [comment]
I defer to @d70-t. But I also agree with him - in retrospect this isn't the best naming but folks have figured out how to work around the inconvenience.

**Comment by d70-t** [comment]
Can we settle on the following:

We'll strongly recommend not to use those problematic characters, but if there's a strong reason for them (like putting an agreed-upon identifier), we still allow them?

@observingClouds could you add a corresponding paragraph (with more complete wording :-)) to `CONTRIBUTING.md` to move this forward ?

**Comment by d70-t** [comment]
This should be settled with #148.
